-- ============================================================
-- Migration 001 : Initial Schema
-- ============================================================
-- Creates the core tables for the Nextra platform:
--   users, badges, user_badges, points_log, streaks,
--   notifications, chat_messages, token_blocklist,
--   and the schema_migrations bookkeeping table.
--
-- Convention: all primary keys are UUID v4 generated by
-- the uuid-ossp extension, except for lightweight
-- serial-based tables (token_blocklist, schema_migrations).
-- ============================================================

BEGIN;

-- ----------------------------------------------------------
-- Extensions
-- ----------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------
-- users
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              UUID        PRIMARY KEY
                                DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) NOT NULL UNIQUE,
    username        VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(150) NOT NULL DEFAULT '',
    avatar_url      TEXT,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    email_confirmed BOOLEAN      NOT NULL DEFAULT FALSE,
    role            VARCHAR(20)  NOT NULL DEFAULT 'user'
                    CHECK (role IN (
                        'user', 'moderator', 'admin'
                    )),
    total_points    INTEGER      NOT NULL DEFAULT 0,
    current_level   INTEGER      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email    ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_role     ON users (role);

-- ----------------------------------------------------------
-- badges
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS badges (
    id              UUID        PRIMARY KEY
                                DEFAULT uuid_generate_v4(),
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT         NOT NULL DEFAULT '',
    icon_url        TEXT,
    category        VARCHAR(50)  NOT NULL DEFAULT 'general',
    points_required INTEGER      NOT NULL DEFAULT 0,
    criteria_json   JSONB        NOT NULL DEFAULT '{}'::JSONB,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_badges_category ON badges (category);

-- ----------------------------------------------------------
-- user_badges  (many-to-many join)
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_badges (
    id        UUID        PRIMARY KEY
                          DEFAULT uuid_generate_v4(),
    user_id   UUID        NOT NULL
              REFERENCES  users (id) ON DELETE CASCADE,
    badge_id  UUID        NOT NULL
              REFERENCES  badges (id) ON DELETE CASCADE,
    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, badge_id)
);

CREATE INDEX idx_user_badges_user_id
    ON user_badges (user_id);
CREATE INDEX idx_user_badges_badge_id
    ON user_badges (badge_id);

-- ----------------------------------------------------------
-- points_log
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS points_log (
    id         UUID        PRIMARY KEY
                           DEFAULT uuid_generate_v4(),
    user_id    UUID        NOT NULL
               REFERENCES  users (id) ON DELETE CASCADE,
    amount     INTEGER     NOT NULL,
    reason     VARCHAR(255) NOT NULL DEFAULT '',
    source     VARCHAR(100) NOT NULL DEFAULT 'system',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_points_log_user_id
    ON points_log (user_id);
CREATE INDEX idx_points_log_created_at
    ON points_log (created_at);

-- ----------------------------------------------------------
-- streaks
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS streaks (
    id                  UUID    PRIMARY KEY
                                DEFAULT uuid_generate_v4(),
    user_id             UUID    NOT NULL UNIQUE
                        REFERENCES users (id)
                        ON DELETE CASCADE,
    current_streak      INTEGER NOT NULL DEFAULT 0,
    longest_streak      INTEGER NOT NULL DEFAULT 0,
    last_activity_date  DATE    NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX idx_streaks_user_id
    ON streaks (user_id);

-- ----------------------------------------------------------
-- notifications
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id            UUID         PRIMARY KEY
                               DEFAULT uuid_generate_v4(),
    user_id       UUID         NOT NULL
                  REFERENCES   users (id) ON DELETE CASCADE,
    title         VARCHAR(255) NOT NULL,
    body          TEXT         NOT NULL DEFAULT '',
    type          VARCHAR(50)  NOT NULL DEFAULT 'info',
    is_read       BOOLEAN      NOT NULL DEFAULT FALSE,
    metadata_json JSONB        NOT NULL DEFAULT '{}'::JSONB,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_user_id
    ON notifications (user_id);
CREATE INDEX idx_notifications_is_read
    ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_created_at
    ON notifications (created_at);

-- ----------------------------------------------------------
-- chat_messages
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
    id          UUID         PRIMARY KEY
                             DEFAULT uuid_generate_v4(),
    user_id     UUID         NOT NULL
                REFERENCES   users (id) ON DELETE CASCADE,
    role        VARCHAR(20)  NOT NULL
                CHECK (role IN (
                    'user', 'assistant', 'system'
                )),
    content     TEXT         NOT NULL,
    provider    VARCHAR(50)  NOT NULL DEFAULT '',
    model       VARCHAR(100) NOT NULL DEFAULT '',
    tokens_used INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_user_id
    ON chat_messages (user_id);
CREATE INDEX idx_chat_messages_created_at
    ON chat_messages (created_at);

-- ----------------------------------------------------------
-- token_blocklist  (lightweight serial PK)
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS token_blocklist (
    id          SERIAL       PRIMARY KEY,
    jti         VARCHAR(255) NOT NULL UNIQUE,
    token_type  VARCHAR(20)  NOT NULL DEFAULT 'access'
                CHECK (token_type IN (
                    'access', 'refresh'
                )),
    blocked_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_token_blocklist_jti
    ON token_blocklist (jti);

-- ----------------------------------------------------------
-- schema_migrations  (bookkeeping for the migrate command)
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    id         SERIAL       PRIMARY KEY,
    filename   VARCHAR(255) NOT NULL UNIQUE,
    applied_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Record this migration
INSERT INTO schema_migrations (filename)
VALUES ('001_initial_schema.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
