/**
 * @file UserCmdGen.cpp
 * @brief SQL generation for user seed.
 */

#include "UserCmd.h"
#include "pbkdf2.h"

#include <fmt/core.h>
#include <nlohmann/json.hpp>

#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace manager
{

using json = nlohmann::json;

static std::string esc(const std::string& s)
{
    std::string o;
    o.reserve(s.size());
    for (char c : s)
        o += (c == '\'') ? "''" : std::string(1, c);
    return o;
}

int UserCmd::seed(
    const std::filesystem::path& seedFile,
    const std::string& outFile)
{
    if (!std::filesystem::exists(seedFile)) {
        std::cerr << "File not found: "
                  << seedFile << "\n";
        return 1;
    }
    std::ifstream f(seedFile);
    json users;
    try { users = json::parse(f); }
    catch (const json::exception& e) {
        std::cerr << "Bad JSON: " << e.what() << "\n";
        return 1;
    }

    std::ostream* os = &std::cout;
    std::ofstream file;
    if (!outFile.empty()) {
        file.open(outFile);
        os = &file;
    }

    *os << "-- Auto-generated user seed.\n"
        << "-- Generated by: ./manager user seed\n\n";

    for (auto& u : users) {
        auto pw   = u.value("password", "");
        auto hash = pw.empty()
            ? std::string("(no-password)")
            : pbkdf2::hash(pw);
        auto role = u.value("role", "user");
        auto conf = u.value(
            "email_confirmed", true)
            ? "true" : "false";
        auto pts = u.value("total_points", 0);
        auto lvl = u.value("current_level", 1);
        *os << fmt::format(
            "INSERT INTO users\n"
            "  (email, username, display_name,\n"
            "   password_hash, role,\n"
            "   email_confirmed,\n"
            "   total_points, current_level)\n"
            "VALUES\n"
            "  ('{}', '{}', '{}',\n"
            "   '{}', '{}',\n"
            "   {}, {}, {})\n"
            "ON CONFLICT (email) DO UPDATE SET\n"
            "  username       = EXCLUDED.username,\n"
            "  display_name   = EXCLUDED.display_name,\n"
            "  password_hash  = EXCLUDED.password_hash,\n"
            "  role           = EXCLUDED.role,\n"
            "  email_confirmed= "
            "EXCLUDED.email_confirmed,\n"
            "  updated_at     = NOW();\n\n",
            esc(u.value("email", "")),
            esc(u.value("username", "")),
            esc(u.value("display_name", "")),
            esc(hash), esc(role), conf, pts, lvl);
    }

    std::cerr << "[user seed] "
              << users.size() << " users processed\n";
    return 0;
}

} // namespace manager
